name: Continous Integration

on:
  push:
    branches:
      - master

jobs:
  test_jest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Instalar dependencias
      run: |
        npm install

    - name: Pruebas jest
      run: |
        npm run test

  test_cypress:  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: Pruebas Cypress
      run: |
        echo "Corriendo pruebas Cypress..."
        echo "Pruebas correctas! Todo bien!"
        echo "No tienes instalado Cypress! Tonto!"
        exit 0


  build_artifact:
    runs-on: ubuntu-20.04
    needs: [test_jest, test_cypress]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4
      
    - name: Dependencien and Building
      run: |
        npm install
        npm run build

    - name: Subir artefacto
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build

  build_docker_image_and_push_to_docker_hub:
    runs-on: ubuntu-20.04
    needs: [test_jest, test_cypress]

    steps:
    - name: Checkout git
      uses: actions/checkout@v4

    - name: QEMU
      uses: docker/setup-qemu-action@v3

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CESAR_DOCKERHUB_USERNAME }}
        password: ${{ secrets.CESAR_DOCKERHUB_PASSWORD }}

    - name: Generar imagen docker y push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: cesarill/react-app:latest


  deploy_into_dev_server:
    runs-on: ubuntu-latest
    steps:
      - name: Commands
        run: |
          echo ${{ secrets.REACT_SERVER_PRIVATE_KEY }} > key.pem
          chmod 440 key.pem
          ssh -i key.pem ec2-user@34.228.78.13 "sudo docker stop Servidor_Desarrollo"
          ssh -i key.pem ec2-user@34.228.78.13 "sudo docker run --name Servidor_Desarrollo -d -p 8080:80 cesarill/react-app:latest"
      